#!/sbin/sh
ulimit -s unlimited
ln  -sf   /sbin/busybox   /sbin/test
ln  -sf   /sbin/busybox   /sbin/nohup
ln  -sf   /sbin/busybox   /sbin/swapoff
ln  -sf   /sbin/busybox   /sbin/uname
ln  -sf   /sbin/busybox   /sbin/tr
ln  -sf   /sbin/busybox   /sbin/catv
ln  -sf   /sbin/busybox   /sbin/fgrep
ln  -sf   /sbin/busybox   /sbin/head
ln  -sf   /sbin/busybox   /sbin/swapon
ln  -sf   /sbin/busybox   /sbin/egrep
ln  -sf   /sbin/busybox   /sbin/md5sum
ln  -sf   /sbin/busybox   /sbin/unyaffs
ln  -sf   /sbin/busybox   /sbin/true
ln  -sf   /sbin/busybox   /sbin/cmp
ln  -sf   /sbin/busybox   /sbin/seq
ln  -sf   /sbin/busybox   /sbin/xargs
ln  -sf   /sbin/busybox   /sbin/usleep
ln  -sf   /sbin/busybox   /sbin/dedupe
ln  -sf   /sbin/busybox   /sbin/uniq
ln  -sf   /sbin/busybox   /sbin/depmod
ln  -sf   /sbin/busybox   /sbin/find
ln  -sf   /sbin/busybox   /sbin/fuser
ln  -sf   /sbin/busybox   /sbin/sed
ln  -sf   /sbin/busybox   /sbin/sha1sum
ln  -sf   /sbin/busybox   /sbin/df
#ln  -sf   /sbin/busybox   /sbin/ln
ln  -sf   /sbin/busybox   /sbin/reboot
ln  -sf   /sbin/busybox   /sbin/mknod
ln  -sf   /sbin/busybox   /sbin/pkill
ln  -sf   /sbin/busybox   /sbin/which
ln  -sf   /sbin/busybox   /sbin/chroot
ln  -sf   /sbin/busybox   /sbin/uudecode
ln  -sf   /sbin/busybox   /sbin/sync
ln  -sf   /sbin/busybox   /sbin/makedevs
ln  -sf   /sbin/busybox   /sbin/tail
ln  -sf   /sbin/busybox   /sbin/lsusb
ln  -sf   /sbin/busybox   /sbin/expand
ln  -sf   /sbin/busybox   /sbin/bunzip2
ln  -sf   /sbin/busybox   /sbin/kill
ln  -sf   /sbin/busybox   /sbin/ls
ln  -sf   /sbin/busybox   /sbin/insmod
#ln  -sf   /sbin/busybox   /sbin/busybox
ln  -sf   /sbin/busybox   /sbin/chattr
ln  -sf   /sbin/busybox   /sbin/sha256sum
ln  -sf   /sbin/busybox   /sbin/chown
ln  -sf   /sbin/busybox   /sbin/install
ln  -sf   /sbin/busybox   /sbin/unexpand
ln  -sf   /sbin/busybox   /sbin/setconsole
ln  -sf   /sbin/busybox   /sbin/mv
ln  -sf   /sbin/busybox   /sbin/nanddump
ln  -sf   /sbin/busybox   /sbin/lzopcat
ln  -sf   /sbin/busybox   /sbin/dc
ln  -sf   /sbin/busybox   /sbin/ash
ln  -sf   /sbin/busybox   /sbin/lzop
ln  -sf   /sbin/busybox   /sbin/chmod
#ln  -sf   /sbin/busybox   /sbin/recovery
ln  -sf   /sbin/busybox   /sbin/less
ln  -sf   /sbin/busybox   /sbin/watch
ln  -sf   /sbin/busybox   /sbin/printf
ln  -sf   /sbin/busybox   /sbin/uptime
ln  -sf   /sbin/busybox   /sbin/grep
ln  -sf   /sbin/busybox   /sbin/nandroid
ln  -sf   /sbin/busybox   /sbin/awk
ln  -sf   /sbin/busybox   /sbin/pgrep
ln  -sf   /sbin/busybox   /sbin/sort
ln  -sf   /sbin/busybox   /sbin/fold
ln  -sf   /sbin/busybox   /sbin/ttysize
ln  -sf   /sbin/busybox   /sbin/lzcat
ln  -sf   /sbin/busybox   /sbin/id
ln  -sf   /sbin/busybox   /sbin/gzip
ln  -sf   /sbin/busybox   /sbin/clear
ln  -sf   /sbin/busybox   /sbin/killall5
ln  -sf   /sbin/busybox   /sbin/cat
ln  -sf   /sbin/busybox   /sbin/whoami
ln  -sf   /sbin/busybox   /sbin/sha512sum
ln  -sf   /sbin/busybox   /sbin/rmmod
ln  -sf   /sbin/busybox   /sbin/fstrim
ln  -sf   /sbin/busybox   /sbin/stat
ln  -sf   /sbin/busybox   /sbin/unlzop
ln  -sf   /sbin/busybox   /sbin/mkswap
ln  -sf   /sbin/busybox   /sbin/[[
ln  -sf   /sbin/busybox   /sbin/lsattr
ln  -sf   /sbin/busybox   /sbin/modinfo
ln  -sf   /sbin/busybox   /sbin/devmem
ln  -sf   /sbin/busybox   /sbin/renice
ln  -sf   /sbin/busybox   /sbin/bbconfig
ln  -sf   /sbin/busybox   /sbin/run-parts
ln  -sf   /sbin/busybox   /sbin/split
ln  -sf   /sbin/busybox   /sbin/du
ln  -sf   /sbin/busybox   /sbin/mkfifo
ln  -sf   /sbin/busybox   /sbin/cpio
ln  -sf   /sbin/busybox   /sbin/readlink
ln  -sf   /sbin/busybox   /sbin/getopt
ln  -sf   /sbin/busybox   /sbin/dirname
ln  -sf   /sbin/busybox   /sbin/killall
ln  -sf   /sbin/busybox   /sbin/lspci
ln  -sf   /sbin/busybox   /sbin/resize
ln  -sf   /sbin/busybox   /sbin/umount
ln  -sf   /sbin/busybox   /sbin/length
ln  -sf   /sbin/busybox   /sbin/dump_image
ln  -sf   /sbin/busybox   /sbin/losetup
ln  -sf   /sbin/busybox   /sbin/ps
ln  -sf   /sbin/busybox   /sbin/xzcat
ln  -sf   /sbin/busybox   /sbin/echo
ln  -sf   /sbin/busybox   /sbin/unix2dos
ln  -sf   /sbin/busybox   /sbin/pwd
ln  -sf   /sbin/busybox   /sbin/date
ln  -sf   /sbin/busybox   /sbin/freeramdisk
ln  -sf   /sbin/busybox   /sbin/getprop
ln  -sf   /sbin/busybox   /sbin/pidof
ln  -sf   /sbin/busybox   /sbin/cut
ln  -sf   /sbin/busybox   /sbin/groups
ln  -sf   /sbin/busybox   /sbin/yes
ln  -sf   /sbin/busybox   /sbin/mkdir
ln  -sf   /sbin/busybox   /sbin/mkfs.ext2
ln  -sf   /sbin/busybox   /sbin/wc
ln  -sf   /sbin/busybox   /sbin/bzip2
ln  -sf   /sbin/busybox   /sbin/blkid
ln  -sf   /sbin/busybox   /sbin/setsid
ln  -sf   /sbin/busybox   /sbin/rm
ln  -sf   /sbin/busybox   /sbin/free
ln  -sf   /sbin/busybox   /sbin/patch
ln  -sf   /sbin/busybox   /sbin/setserial
ln  -sf   /sbin/busybox   /sbin/mountpoint
ln  -sf   /sbin/busybox   /sbin/nice
ln  -sf   /sbin/busybox   /sbin/bu
ln  -sf   /sbin/busybox   /sbin/rmdir
ln  -sf   /sbin/busybox   /sbin/chgrp
ln  -sf   /sbin/busybox   /sbin/fdisk
ln  -sf   /sbin/busybox   /sbin/rdev
ln  -sf   /sbin/busybox   /sbin/env
ln  -sf   /sbin/busybox   /sbin/hexdump
ln  -sf   /sbin/busybox   /sbin/setprop
ln  -sf   /sbin/busybox   /sbin/strings
ln  -sf   /sbin/busybox   /sbin/modprobe
ln  -sf   /sbin/busybox   /sbin/more
ln  -sf   /sbin/busybox   /sbin/cal
ln  -sf   /sbin/busybox   /sbin/sleep
ln  -sf   /sbin/busybox   /sbin/false
ln  -sf   /sbin/busybox   /sbin/nandwrite
ln  -sf   /sbin/busybox   /sbin/top
ln  -sf   /sbin/busybox   /sbin/rev
ln  -sf   /sbin/busybox   /sbin/tac
ln  -sf   /sbin/busybox   /sbin/cksum
ln  -sf   /sbin/busybox   /sbin/gunzip
ln  -sf   /sbin/busybox   /sbin/od
ln  -sf   /sbin/busybox   /sbin/basename
ln  -sf   /sbin/busybox   /sbin/time
ln  -sf   /sbin/busybox   /sbin/lsmod
ln  -sf   /sbin/busybox   /sbin/unzip
ln  -sf   /sbin/busybox   /sbin/erase_image
ln  -sf   /sbin/busybox   /sbin/mount
ln  -sf   /sbin/busybox   /sbin/dos2unix
ln  -sf   /sbin/busybox   /sbin/tee
ln  -sf   /sbin/busybox   /sbin/touch
ln  -sf   /sbin/busybox   /sbin/reset
ln  -sf   /sbin/busybox   /sbin/make_ext4fs
ln  -sf   /sbin/busybox   /sbin/sysctl
ln  -sf   /sbin/busybox   /sbin/[
ln  -sf   /sbin/busybox   /sbin/edify
ln  -sf   /sbin/busybox   /sbin/volume
ln  -sf   /sbin/busybox   /sbin/cp
ln  -sf   /sbin/busybox   /sbin/unxz
ln  -sf   /sbin/busybox   /sbin/pstree
ln  -sf   /sbin/busybox   /sbin/mkyaffs2image
ln  -sf   /sbin/busybox   /sbin/bzcat
#ln  -sf   /sbin/busybox   /sbin/sh
ln  -sf   /sbin/busybox   /sbin/diff
ln  -sf   /sbin/busybox   /sbin/tar
ln  -sf   /sbin/busybox   /sbin/expr
ln  -sf   /sbin/busybox   /sbin/dmesg
ln  -sf   /sbin/busybox   /sbin/dd
ln  -sf   /sbin/busybox   /sbin/zcat
ln  -sf   /sbin/busybox   /sbin/uuencode
ln  -sf   /sbin/busybox   /sbin/printenv
ln  -sf   /sbin/busybox   /sbin/unlzma
ln  -sf   /sbin/busybox   /sbin/stty
ln  -sf   /sbin/busybox   /sbin/minizip
ln  -sf   /sbin/busybox   /sbin/realpath
ln  -sf   /sbin/busybox   /sbin/flash_image
ln  -sf   /sbin/busybox   /sbin/mktemp
